name: CI/Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 3

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: package-update
        uses: ghustavh97/actions-package-update@test
        env:
          AUTHOR_EMAIL: oslllo.com@gmail.com
          AUTHOR_NAME: oslllo
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
        with:
          args: -u --packageFile package.json --loglevel verbose
